1、除： /；整除： //；
2、位运算：
print(bin(4))  # 0b100
print(bin(5))  # 0b101
print(bin(~4), ~4)  # -0b101 -5 按位取反
print(bin(4 & 5), 4 & 5)  # 0b100 4 按位与
print(bin(4 | 5), 4 | 5)  # 0b101 5 按位或
print(bin(4 ^ 5), 4 ^ 5)  # 0b1 1 按位异或
print(bin(4 << 2), 4 << 2)  # 0b10000 16 左移
print(bin(4 >> 2), 4 >> 2)  # 0b1 1右移
3、其他运算符：in; not in; is; not is;
4、基本类型：整型、浮点型、布尔型
容器类型：字符串、元组、列表、字典和集合
5、assert 关键词：断言，当这个关键词后边的条件为 False 时，程序自动崩溃并抛出AssertionError的异常。
assert 3 > 7
# AssertionError
6、while可以加else：
while 布尔表达式:
    代码块
else:
    代码块
7、for else：
当for循环正常执行完的情况下，执行else输出，如果for循环中执行了跳出循环的语句，比如 break，将不执行else代码块的内容，与while - else语句一样。
8、enumerate(sequence, [start=0])
sequence：一个序列、迭代器或其他支持迭代对象。
start：下标起始位置。
返回 enumerate(枚举) 对象
9、Python 标准异常总结

BaseException：所有异常的 基类
Exception：常规异常的 基类
StandardError：所有的内建标准异常的基类
ArithmeticError：所有数值计算异常的基类
FloatingPointError：浮点计算异常
OverflowError：数值运算超出最大限制
ZeroDivisionError：除数为零
AssertionError：断言语句（assert）失败
AttributeError：尝试访问未知的对象属性
EOFError：没有内建输入，到达EOF标记
EnvironmentError：操作系统异常的基类
IOError：输入/输出操作失败
OSError：操作系统产生的异常（例如打开一个不存在的文件）
WindowsError：系统调用失败
ImportError：导入模块失败的时候
KeyboardInterrupt：用户中断执行
LookupError：无效数据查询的基类
IndexError：索引超出序列的范围
KeyError：字典中查找一个不存在的关键字
MemoryError：内存溢出（可通过删除对象释放内存）
NameError：尝试访问一个不存在的变量
UnboundLocalError：访问未初始化的本地变量
ReferenceError：弱引用试图访问已经垃圾回收了的对象
RuntimeError：一般的运行时异常
NotImplementedError：尚未实现的方法
SyntaxError：语法错误导致的异常
IndentationError：缩进错误导致的异常
TabError：Tab和空格混用
SystemError：一般的解释器系统异常
TypeError：不同类型间的无效操作
ValueError：传入无效的参数
UnicodeError：Unicode相关的异常
UnicodeDecodeError：Unicode解码时的异常
UnicodeEncodeError：Unicode编码错误导致的异常
UnicodeTranslateError：Unicode转换错误导致的异常
10、Python标准警告总结

Warning：警告的基类
DeprecationWarning：关于被弃用的特征的警告
FutureWarning：关于构造将来语义会有改变的警告
UserWarning：用户代码生成的警告
PendingDeprecationWarning：关于特性将会被废弃的警告
RuntimeWarning：可疑的运行时行为(runtime behavior)的警告
SyntaxWarning：可疑语法的警告
ImportWarning：用于在导入模块过程中触发的警告
UnicodeWarning：与Unicode相关的警告
BytesWarning：与字节或字节码相关的警告
ResourceWarning：与资源使用相关的警告
11、try:
    检测范围
except:
    出现异常后的处理代码
else:
    如果没有异常执行这块代码
12、使用raise抛出一个指定的异常
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
